### ISSUE TITLE
 Is it safe for NSClassFromString?

### ISSUE THREAD

**Issue by leavez** [intercom/cocoapods-mangle#13]
if a lib use `NSClassFromString` with an custom class name, although this should be avoided, I think it's may be not work after mangling.

**Comment by jtreanor** [comment]
Yes, you're absolutely correct. Once mangled, `NSClassFromString(@"MyClass")` won't work (it would need to be `NSClassFromString(@"Prefix_MyClass")`).

I don't think there is any way this limitation could be avoided. Perhaps a note in the README would be a good idea.

**Comment by bboyle18** [comment]
👋 
I updated the Readme to reflect this.
https://github.com/intercom/cocoapods-mangle/pull/14

Brian
