### ISSUE TITLE
AFNetworking 4.0.1 fails to build after cocoapods-mangle

### ISSUE THREAD

**Issue by cwheeler42** [intercom/cocoapods-mangle#23]
I am trying to use AFNetworking in a Framework and when using cocoapods-mangle (latest) on the latest release of the AFNetworking pod, it fails to build with some errors I'm not able to resolve.

Here is the podfile I'm using (this is just a test app I've built to eliminate any issues with my framework and isolate the problem):

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "12.0"
plugin 'cocoapods-mangle', targets: ['CMTestApp'],
                           mangle_prefix: 'CMTestApp_',
                           xcconfig_path: 'cmtestapp-mangle.xcconfig'

target 'CMTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for CMTestApp
  pod 'AFNetworking', '~> 4.0'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

```
The only pod I'm including is AFNetworking and this happens whether I include the additional configuration for cocoapods-mangle or go with the defaults.

The error I'm getting when trying to build seems to relate to a protocol definition <AFURLResponseSerialization> inside AFNetworking that is no longer found after the mangling:

> CompileC /Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AFNetworking.build/Objects-normal/x86_64/AFURLSessionManager.o /Users/cwheeler/Development/CMTestApp/Pods/AFNetworking/AFNetworking/AFURLSessionManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'AFNetworking' from project 'Pods')
>     cd /Users/cwheeler/Development/CMTestApp/Pods
>     export LANG\=en_US.US-ASCII
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios9.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path\=/Users/cwheeler/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/cwheeler/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DAFAutoPurgingImageCache\=CMTestApp_AFAutoPurgingImageCache -DAFCachedImage\=CMTestApp_AFCachedImage -DAFHTTPSessionManager\=CMTestApp_AFHTTPSessionManager -DAFImageDownloadReceipt\=CMTestApp_AFImageDownloadReceipt -DAFImageDownloader\=CMTestApp_AFImageDownloader -DAFImageDownloaderMergedTask\=CMTestApp_AFImageDownloaderMergedTask -DAFImageDownloaderResponseHandler\=CMTestApp_AFImageDownloaderResponseHandler -DAFNetworkActivityIndicatorManager\=CMTestApp_AFNetworkActivityIndicatorManager -DPodsDummy_AFNetworking\=CMTestApp_PodsDummy_AFNetworking -DAFNetworkReachabilityManager\=CMTestApp_AFNetworkReachabilityManager -DAFSecurityPolicy\=CMTestApp_AFSecurityPolicy -DAFHTTPBodyPart\=CMTestApp_AFHTTPBodyPart -DAFHTTPRequestSerializer\=CMTestApp_AFHTTPRequestSerializer -DAFJSONRequestSerializer\=CMTestApp_AFJSONRequestSerializer -DAFMultipartBodyStream\=CMTestApp_AFMultipartBodyStream -DAFPropertyListRequestSerializer\=CMTestApp_AFPropertyListRequestSerializer -DAFQueryStringPair\=CMTestApp_AFQueryStringPair -DAFStreamingMultipartFormData\=CMTestApp_AFStreamingMultipartFormData -DAFCompoundResponseSerializer\=CMTestApp_AFCompoundResponseSerializer -DAFHTTPResponseSerializer\=CMTestApp_AFHTTPResponseSerializer -DAFImageResponseSerializer\=CMTestApp_AFImageResponseSerializer -DAFJSONResponseSerializer\=CMTestApp_AFJSONResponseSerializer -DAFPropertyListResponseSerializer\=CMTestApp_AFPropertyListResponseSerializer -DAFXMLParserResponseSerializer\=CMTestApp_AFXMLParserResponseSerializer -DAFURLSessionManager\=CMTestApp_AFURLSessionManager -DAFURLSessionManagerTaskDelegate\=CMTestApp_AFURLSessionManagerTaskDelegate -DAFActivityIndicatorViewNotificationObserver\=CMTestApp_AFActivityIndicatorViewNotificationObserver -DAFRefreshControlNotificationObserver\=CMTestApp_AFRefreshControlNotificationObserver -DAFNetworkingReachabilityDidChangeNotification\=CMTestApp_AFNetworkingReachabilityDidChangeNotification -DAFNetworkingReachabilityNotificationStatusItem\=CMTestApp_AFNetworkingReachabilityNotificationStatusItem -DAFNetworkingOperationFailingURLRequestErrorKey\=CMTestApp_AFNetworkingOperationFailingURLRequestErrorKey -DAFURLRequestSerializationErrorDomain\=CMTestApp_AFURLRequestSerializationErrorDomain -DkAFUploadStream3GSuggestedDelay\=CMTestApp_kAFUploadStream3GSuggestedDelay -DkAFUploadStream3GSuggestedPacketSize\=CMTestApp_kAFUploadStream3GSuggestedPacketSize -DAFNetworkingOperationFailingURLResponseDataErrorKey\=CMTestApp_AFNetworkingOperationFailingURLResponseDataErrorKey -DAFNetworkingOperationFailingURLResponseErrorKey\=CMTestApp_AFNetworkingOperationFailingURLResponseErrorKey -DAFURLResponseSerializationErrorDomain\=CMTestApp_AFURLResponseSerializationErrorDomain -DAFNetworkingTaskDidCompleteAssetPathKey\=CMTestApp_AFNetworkingTaskDidCompleteAssetPathKey -DAFNetworkingTaskDidCompleteErrorKey\=CMTestApp_AFNetworkingTaskDidCompleteErrorKey -DAFNetworkingTaskDidCompleteNotification\=CMTestApp_AFNetworkingTaskDidCompleteNotification -DAFNetworkingTaskDidCompleteResponseDataKey\=CMTestApp_AFNetworkingTaskDidCompleteResponseDataKey -DAFNetworkingTaskDidCompleteResponseSerializerKey\=CMTestApp_AFNetworkingTaskDidCompleteResponseSerializerKey -DAFNetworkingTaskDidCompleteSerializedResponseKey\=CMTestApp_AFNetworkingTaskDidCompleteSerializedResponseKey -DAFNetworkingTaskDidCompleteSessionTaskMetrics\=CMTestApp_AFNetworkingTaskDidCompleteSessionTaskMetrics -DAFNetworkingTaskDidResumeNotification\=CMTestApp_AFNetworkingTaskDidResumeNotification -DAFNetworkingTaskDidSuspendNotification\=CMTestApp_AFNetworkingTaskDidSuspendNotification -DAFURLSessionDidInvalidateNotification\=CMTestApp_AFURLSessionDidInvalidateNotification -DAFURLSessionDownloadTaskDidFailToMoveFileNotification\=CMTestApp_AFURLSessionDownloadTaskDidFailToMoveFileNotification -DAFURLSessionDownloadTaskDidMoveFileSuccessfullyNotification\=CMTestApp_AFURLSessionDownloadTaskDidMoveFileSuccessfullyNotification -DAFStringFromNetworkReachabilityStatus\=CMTestApp_AFStringFromNetworkReachabilityStatus -DAFPercentEscapedStringFromString\=CMTestApp_AFPercentEscapedStringFromString -DAFQueryStringFromParameters\=CMTestApp_AFQueryStringFromParameters -DAFQueryStringPairsFromDictionary\=CMTestApp_AFQueryStringPairsFromDictionary -DAFQueryStringPairsFromKeyAndValue\=CMTestApp_AFQueryStringPairsFromKeyAndValue -DAFJSONObjectByRemovingKeysWithNullValues\=CMTestApp_AFJSONObjectByRemovingKeysWithNullValues -D__clang_at_available_requires_core_foundation_framework\=CMTestApp___clang_at_available_requires_core_foundation_framework -DsetSharedImageDownloader\=setCMTestApp_sharedImageDownloader -DsharedImageDownloader\=CMTestApp_sharedImageDownloader -DsetResponseSerializer\=setCMTestApp_responseSerializer -DresponseSerializer\=CMTestApp_responseSerializer -DsetSessionManager\=setCMTestApp_sessionManager -DsessionManager\=CMTestApp_sessionManager -Daf_safeImageWithData\=CMTestApp_af_safeImageWithData -Daf_notificationObserver\=CMTestApp_af_notificationObserver -DsetAnimatingWithStateOfTask\=CMTestApp_setAnimatingWithStateOfTask -DcancelBackgroundImageDownloadTaskForState\=CMTestApp_cancelBackgroundImageDownloadTaskForState -DcancelImageDownloadTaskForState\=CMTestApp_cancelImageDownloadTaskForState -DisActiveBackgroundTaskURLEqualToURLRequest\=CMTestApp_isActiveBackgroundTaskURLEqualToURLRequest -DisActiveTaskURLEqualToURLRequest\=CMTestApp_isActiveTaskURLEqualToURLRequest -DsetBackgroundImageForState\=CMTestApp_setBackgroundImageForState -DsetImageForState\=CMTestApp_setImageForState -Daf_backgroundImageDownloadReceiptForState\=CMTestApp_af_backgroundImageDownloadReceiptForState -Daf_imageDownloadReceiptForState\=CMTestApp_af_imageDownloadReceiptForState -Daf_setBackgroundImageDownloadReceipt\=CMTestApp_af_setBackgroundImageDownloadReceipt -Daf_setImageDownloadReceipt\=CMTestApp_af_setImageDownloadReceipt -DcancelImageDownloadTask\=CMTestApp_cancelImageDownloadTask -DclearActiveDownloadInformation\=CMTestApp_clearActiveDownloadInformation -DsetImageWithURL\=CMTestApp_setImageWithURL -DsetImageWithURLRequest\=CMTestApp_setImageWithURLRequest -Daf_activeImageDownloadReceipt\=CMTestApp_af_activeImageDownloadReceipt -Daf_setActiveImageDownloadReceipt\=CMTestApp_af_setActiveImageDownloadReceipt -Daf_downloadProgressAnimated\=CMTestApp_af_downloadProgressAnimated -Daf_setDownloadProgressAnimated\=CMTestApp_af_setDownloadProgressAnimated -Daf_setUploadProgressAnimated\=CMTestApp_af_setUploadProgressAnimated -Daf_uploadProgressAnimated\=CMTestApp_af_uploadProgressAnimated -DobserveValueForKeyPath\=CMTestApp_observeValueForKeyPath -DsetProgressWithDownloadProgressOfTask\=CMTestApp_setProgressWithDownloadProgressOfTask -DsetProgressWithUploadProgressOfTask\=CMTestApp_setProgressWithUploadProgressOfTask -DsetRefreshingWithStateOfTask\=CMTestApp_setRefreshingWithStateOfTask -DloadRequest\=CMTestApp_loadRequest -Daf_URLSessionTask\=CMTestApp_af_URLSessionTask -Daf_setURLSessionTask\=CMTestApp_af_setURLSessionTask -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path /Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Index/DataStore -iquote /Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AFNetworking.build/AFNetworking-generated-files.hmap -I/Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AFNetworking.build/AFNetworking-own-target-headers.hmap -I/Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AFNetworking.build/AFNetworking-all-target-headers.hmap -iquote /Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AFNetworking.build/AFNetworking-project-headers.hmap -I/Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Products/Debug-iphonesimulator/AFNetworking/include -I/Users/cwheeler/Development/CMTestApp/Pods/Headers/Private -I/Users/cwheeler/Development/CMTestApp/Pods/Headers/Private/AFNetworking -I/Users/cwheeler/Development/CMTestApp/Pods/Headers/Public -I/Users/cwheeler/Development/CMTestApp/Pods/Headers/Public/AFNetworking -I/Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AFNetworking.build/DerivedSources-normal/x86_64 -I/Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AFNetworking.build/DerivedSources/x86_64 -I/Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AFNetworking.build/DerivedSources -F/Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Products/Debug-iphonesimulator/AFNetworking -include /Users/cwheeler/Development/CMTestApp/Pods/Target\ Support\ Files/AFNetworking/AFNetworking-prefix.pch -MMD -MT dependencies -MF /Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AFNetworking.build/Objects-normal/x86_64/AFURLSessionManager.d --serialize-diagnostics /Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AFNetworking.build/Objects-normal/x86_64/AFURLSessionManager.dia -c /Users/cwheeler/Development/CMTestApp/Pods/AFNetworking/AFNetworking/AFURLSessionManager.m -o /Users/cwheeler/Library/Developer/Xcode/DerivedData/CMTestApp-ccctclzbtmjfweghvmquteoacdsc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/AFNetworking.build/Objects-normal/x86_64/AFURLSessionManager.o
> 
> /Users/cwheeler/Development/CMTestApp/Pods/AFNetworking/AFNetworking/AFURLSessionManager.m:716:5: error: use of undeclared identifier '_responseSerializer'
>     _responseSerializer = responseSerializer;
>     ^
> 1 error generated.

Any help or suggestions appreciated. I am happy to provide additional info including my test project if needed.

**Comment by cynicer** [comment]
https://github.com/AFNetworking/AFNetworking
AFNetworking is archived for a while, I suggest upgrading to Alamofire first.
